gremlin:
  endpoint: localhost
  port: 8182 #443
  #username: admin # /dbs/your-db-name/colls/your-collection-name
  #password: admin #your-password
  telemetryAllowed: true # set false to disable telemetry
  sslEnabled: false
