gremlin:
  endpoint: localhost
  port: 8182 //443
  username: /dbs/your-db-name/colls/your-collection-name
  password: your-password
  telemetryAllowed: true # set false to disable telemetry
  sslEnabled: false
